// Package proxy manages the host-wide reverse proxy that fronts
// every deployment with a hostname route. A single Caddy container
// (`impreza_caddy`) runs per host, joined to a shared Docker network
// (`impreza-proxy`) that deployment containers also join; Caddy
// forwards `hostname → container:port` and obtains Let's Encrypt
// certificates automatically.
//
// Persistence layout under stateDir/proxy/:
//
//	Caddyfile               # generated by concatenating fragments
//	data/                   # Caddy's cert + ACME state (mounted /data)
//	config/                 # Caddy's runtime config (mounted /config)
//	deployments/
//	    dpl_xxx.caddy       # per-deployment fragment
//	    dpl_yyy.caddy
//
// The agent calls EnsureNetwork + EnsureRunning before applying the
// first route; subsequent route changes only trigger Caddyfile
// regeneration + `caddy reload`.
package proxy

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"
	"unicode/utf8"
)

const (
	// NetworkName is the shared Docker network Caddy + apps join.
	NetworkName = "impreza-proxy"
	// ContainerName is the singleton Caddy container per host.
	ContainerName = "impreza_caddy"
	// Image is the Caddy image. We ship a custom build that bundles
	// the caddy-dns-impreza module on top of caddy:<ver>-alpine so
	// Caddy can complete ACME DNS-01 challenges by proxying TXT-record
	// writes through the Impreza public API (the operator's CF token
	// stays IP-restricted on the control plane — see
	// caddy-dns-impreza/README.md for the rationale). This build, published
	// as caddy:2.11.4-s1, adds the Impreza Shield stack: Coraza WAF with the
	// embedded OWASP CRS, the shield_pow proof-of-work gate and
	// shield_rate_limit. It is pinned by the digest of its multi-arch index;
	// EnsureRunning recreates the proxy container whenever the running image
	// differs, keeping the bind-mounted /data. The 2-cf stream keeps serving
	// agents up to 0.6.21 unchanged.
	//
	Image = "ghcr.io/imprezahost/caddy@sha256:2635ee3746c1cf3c8e2a9c91400bf5c016068a836025b4ade04d5a7dd707d83f"
	// Env-var names the Caddy container reads to authenticate against
	// the Impreza public API on every DNS-01 present/cleanup. These
	// are set by SetImprezaCredentials in the env-file EnsureRunning passes
	// with `--env-file`, and
	// referenced from per-deployment fragments as
	// `dns impreza {env.IMPREZA_AGENT_ID} {env.IMPREZA_AGENT_SECRET}`.
	// Phase 9.11d v2 — replaces the CADDY_CF_API_TOKEN of v1 (which
	// exposed CF write access to every customer VPS).
	ImprezaAgentIDEnvVar     = "IMPREZA_AGENT_ID"
	ImprezaAgentSecretEnvVar = "IMPREZA_AGENT_SECRET"
	ImprezaAPIURLEnvVar      = "IMPREZA_API_URL"
)

// Route describes one hostname → upstream mapping the proxy programs.
// Set Hostname for a clearnet site (Caddy auto-TLS via Let's Encrypt),
// or OnionAddr for an onion service block, or both: a single Route
// can emit both fragments pointing at the same upstream.
type Route struct {
	// Hostname is the public clearnet name Caddy listens on (e.g.
	// vault.example.com). Leave empty for onion-only routes.
	Hostname string
	// OnionAddr is the .onion address Tor publishes (e.g.
	// abc...xyz.onion). When set, an `http://<addr> { ... }` block
	// is emitted alongside / instead of the clearnet block.
	OnionAddr string
	// Upstream is the `container:port` Caddy forwards to. The container
	// MUST be joined to NetworkName so Caddy can resolve it.
	Upstream string
	// TLSMode is "letsencrypt" | "internal" | "none". "letsencrypt" is
	// the only one wired in this phase; the others come later.
	TLSMode string
	// TLSEmail is optional contact for Let's Encrypt.
	TLSEmail string
	// TLSDNSProvider (Phase 9.11d) opts this route into ACME DNS-01
	// challenge using the named provider instead of the default
	// HTTP-01. Currently only "cloudflare" is implemented. The CF API
	// token must be available to the Caddy container via the env-var
	// CloudflareTokenEnvVar — see SetCloudflareToken.
	TLSDNSProvider string
	// BasicAuth (protected previews) gates the route behind HTTP Basic
	// auth. Carries only the bcrypt hash of the server-generated
	// password — the plaintext never leaves the platform's creation
	// response. Validated on write; an invalid hash is refused, never
	// silently dropped (that would serve the route publicly).
	BasicAuth *BasicAuth
	// Shield (capability shield-v1) stamps the deployment's Impreza
	// Shield policy (profile + mode) onto both the clearnet and onion site
	// blocks. Nil means profile off — no directives.
	Shield *ShieldConfig
}

// BasicAuth is one HTTP Basic credential gate for a route.
type BasicAuth struct {
	Username   string
	BCryptHash string
}

// basicAuthUsernameRe keeps the Caddyfile free of injection: the username
// lands inside a `basic_auth { user hash }` block, so it can never contain
// whitespace, braces or quotes.
var basicAuthUsernameRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,31}$`)

// basicAuthHashRe is a bcrypt hash with cost >= 10 ($2a$/$2b$/$2y$). Lower
// costs are refused: below 10 the hash is fast enough to brute-force
// online against the proxy.
var basicAuthHashRe = regexp.MustCompile(`^\$2[aby]\$(1[0-9]|2[0-9]|3[01])\$[./A-Za-z0-9]{53}$`)

// validateBasicAuth refuses malformed credentials rather than emitting a
// fragment Caddy would reject (breaking every other route on reload) or —
// worse — silently skipping the gate.
func validateBasicAuth(b *BasicAuth) error {
	if b == nil {
		return nil
	}
	if !basicAuthUsernameRe.MatchString(b.Username) {
		return fmt.Errorf("basic_auth username %q is not a safe label", b.Username)
	}
	if !basicAuthHashRe.MatchString(b.BCryptHash) {
		return fmt.Errorf("basic_auth hash is not a bcrypt hash with cost >= 10")
	}
	return nil
}

// Caddy owns the host's reverse-proxy state.
type Caddy struct {
	StateDir      string // <agent-state>/proxy
	Log           *slog.Logger
	switchReload  func(context.Context) error           // test seam for reload failure boundaries
	containerList func(context.Context) ([]byte, error) // test seam for Docker availability

	// Proxy-metrics scrape state: previous exposition snapshot for
	// per-cycle deltas. Memory only, deployment-labeled series only.
	scrapeMu   sync.Mutex
	lastScrape map[scrapeKey]float64

	// imageEnv caches the pinned image's default environment names, for the
	// env-file comparison. Memory only.
	imageEnv []string
}

// New constructs a Caddy under <agentStateDir>/proxy.
func New(agentStateDir string, log *slog.Logger) *Caddy {
	return &Caddy{
		StateDir: filepath.Join(agentStateDir, "proxy"),
		Log:      log,
	}
}

// EnsureNetwork creates the shared Docker network if absent.
// Idempotent — repeated calls are cheap.
func (c *Caddy) EnsureNetwork(ctx context.Context) error {
	// `docker network inspect` exits 0 when present, non-zero otherwise.
	if out, err := exec.CommandContext(ctx, "docker", "network", "inspect", NetworkName).CombinedOutput(); err == nil {
		_ = out
		return nil
	}
	c.Log.Info("proxy: creating shared docker network", "network", NetworkName)
	if out, err := exec.CommandContext(ctx, "docker", "network", "create", NetworkName).CombinedOutput(); err != nil {
		return fmt.Errorf("docker network create %s: %v: %s", NetworkName, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// proxySpecLabel carries, on the proxy container, the digest of the exact
// `docker run` arguments that created it. It holds no secret: the
// environment is compared on its own, against the container's copy.
const proxySpecLabel = "impreza.proxy.spec"

// EnsureRunning starts the Caddy container if not already running.
// Idempotent. Mounts the Caddyfile + data dirs from StateDir.
//
// Phase 9.11d additions:
//   - Always passes `--env-file <stateDir>/proxy/caddy.env` so the
//     CloudflareTokenEnvVar set by SetCloudflareToken reaches Caddy
//     (the env-var is referenced from per-deployment fragments via
//     `{env.CADDY_CF_API_TOKEN}` for DNS-01 challenges).
//
// The proxy is shared by every app on the host, and a recreation cuts
// HTTPS for all of them, so an existing container is recreated only when
// it no longer matches what this agent would run: another image, a
// spec label that differs or is missing (created by an older agent), or an
// environment other than the env-file's current content. Docker copies the
// env-file into the container at creation and `docker restart` keeps that
// copy, which is why the environment is read from the container itself.
// The previous check looked for the env-file among the bind mounts, where
// `--env-file` never appears, so every deploy with a route recreated the
// proxy. Data dir is bind-mounted so existing certs survive a recreation.
func (c *Caddy) EnsureRunning(ctx context.Context) error {
	if err := c.guardRoutingSwitch(); err != nil {
		return err
	}
	if err := c.ensureDirs(); err != nil {
		return err
	}
	// First write of the Caddyfile happens on first ApplyRoutes call;
	// EnsureRunning ensures it at least exists so Caddy doesn't crash
	// on missing config when there are zero deployments yet.
	caddyfile := filepath.Join(c.StateDir, "Caddyfile")
	if _, err := os.Stat(caddyfile); os.IsNotExist(err) {
		if err := os.WriteFile(caddyfile, []byte("# managed by impreza-agent — do not edit\n"), 0o644); err != nil {
			return fmt.Errorf("write empty Caddyfile: %w", err)
		}
	}

	// Ensure caddy.env exists (empty placeholder is fine — Caddy
	// tolerates the env-file containing zero vars). Set 0o600 because
	// when populated by SetCloudflareToken it holds an API token.
	envFile := c.envFilePath()
	if _, err := os.Stat(envFile); os.IsNotExist(err) {
		if err := os.WriteFile(envFile, []byte("# managed by impreza-agent — do not edit\n"), 0o600); err != nil {
			return fmt.Errorf("write empty caddy.env: %w", err)
		}
	}

	// The environment the container must carry, parsed the way the Docker
	// CLI reads an env-file. A file the CLI would refuse stops here, before
	// the serving proxy is touched.
	wantEnv, err := readProxyEnvFile(envFile)
	if err != nil {
		return fmt.Errorf("proxy environment file unusable; the running proxy was kept: %w", err)
	}
	args := c.runArgs(envFile, caddyfile)
	spec := proxySpecDigest(args)

	// Inspect the existing container, if any, in one round-trip. The
	// output carries the container's environment, credentials included:
	// it is only compared, never logged or returned.
	type containerInfo struct {
		Status string
		Image  string
		Spec   string
		Env    []string
	}
	var existing *containerInfo
	if out, err := exec.CommandContext(ctx, "docker", "inspect", "--format",
		`{"Status":{{json .State.Status}},"Image":{{json .Config.Image}},"Spec":{{json (index .Config.Labels "`+proxySpecLabel+`")}},"Env":{{json .Config.Env}}}`,
		ContainerName).Output(); err == nil {
		var info containerInfo
		if json.Unmarshal(out, &info) == nil {
			existing = &info
		}
	}

	if existing != nil {
		reason := ""
		switch {
		case existing.Image != Image:
			reason = "image"
		case existing.Spec == "":
			reason = "created by an older agent"
		case existing.Spec != spec:
			reason = "container settings"
		case !proxyEnvMatches(wantEnv, existing.Env, c.proxyImageDefaultEnv(ctx)):
			reason = "environment"
		}
		if reason != "" {
			c.Log.Info("proxy: recreating caddy container",
				"reason", reason, "old_image", existing.Image, "new_image", Image)
			if err := c.removeContainer(ctx); err != nil {
				return err
			}
		} else if existing.Status == "running" {
			return c.reconcileTorEgressNetworks(ctx)
		} else {
			// Exists, same shape, but not running — start it.
			c.Log.Info("proxy: starting existing caddy container", "state", existing.Status)
			if out, err := exec.CommandContext(ctx, "docker", "start", ContainerName).CombinedOutput(); err != nil {
				return fmt.Errorf("docker start %s: %v: %s", ContainerName, err, strings.TrimSpace(string(out)))
			}
			return c.reconcileTorEgressNetworks(ctx)
		}
	}

	// Doesn't exist (or was just removed for recreation) — run it, stamped
	// with the digest of these exact arguments.
	c.Log.Info("proxy: launching caddy container", "image", Image)
	run := append([]string{}, args[:len(args)-1]...)
	run = append(run, "--label", proxySpecLabel+"="+spec, Image)
	if out, err := exec.CommandContext(ctx, "docker", run...).CombinedOutput(); err != nil {
		return fmt.Errorf("docker run caddy: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return c.reconcileTorEgressNetworks(ctx)
}

// runArgs is the proxy container's `docker run`, image last, without the
// spec label EnsureRunning adds.
func (c *Caddy) runArgs(envFile, caddyfile string) []string {
	return []string{
		"run", "-d",
		"--name", ContainerName,
		"--restart", "unless-stopped",
		"--network", NetworkName,
		"-p", "80:80",
		"-p", "443:443",
		"-p", "443:443/udp", // HTTP/3
		"--env-file", envFile,
		"-v", caddyfile + ":/etc/caddy/Caddyfile:ro",
		"-v", filepath.Join(c.StateDir, "data") + ":/data",
		"-v", filepath.Join(c.StateDir, "config") + ":/config",
		Image,
	}
}

// proxySpecDigest names one exact argument list. The env-file enters by
// path only; its content is compared against the container separately.
func proxySpecDigest(args []string) string {
	h := sha256.New()
	for _, arg := range args {
		h.Write([]byte(arg))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}

// readProxyEnvFile returns the KEY=VALUE entries `docker run --env-file`
// would set, following the Docker CLI's reader: a leading UTF-8 BOM and
// leading whitespace dropped, `#` comments and blank lines skipped, the
// value taken verbatim after the first `=`, and a bare KEY passed through
// from this process's environment only when set there.
func readProxyEnvFile(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var entries []string
	scanner := bufio.NewScanner(f)
	for n := 1; scanner.Scan(); n++ {
		raw := scanner.Bytes()
		if !utf8.Valid(raw) {
			return nil, fmt.Errorf("line %d is not valid UTF-8", n)
		}
		if n == 1 {
			raw = bytes.TrimPrefix(raw, []byte{0xEF, 0xBB, 0xBF})
		}
		line := strings.TrimLeftFunc(string(raw), unicode.IsSpace)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, hasValue := strings.Cut(line, "=")
		key = strings.TrimLeft(key, " \t")
		if key == "" || strings.ContainsAny(key, " \t") {
			return nil, fmt.Errorf("line %d has no valid variable name", n)
		}
		if hasValue {
			entries = append(entries, key+"="+value)
		} else if value, ok := os.LookupEnv(key); ok {
			entries = append(entries, key+"="+value)
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

// proxyImageDefaultEnv resolves, from the image the agent pins, the
// environment entries the image itself provides. Everything else in the
// container must come from the env-file: a variable that left the file is
// a leftover the recreation must pick up. Fetched lazily and only
// cached on success, so an image change is picked up on the next deploy.
func (c *Caddy) proxyImageDefaultEnv(ctx context.Context) []string {
	if c.imageEnv != nil {
		return c.imageEnv
	}
	out, err := exec.CommandContext(ctx, "docker", "image", "inspect", "--format", "{{json .Config.Env}}", Image).Output()
	if err != nil {
		return nil
	}
	var entries []string
	if json.Unmarshal(out, &entries) != nil {
		return nil
	}
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if key, _, found := strings.Cut(entry, "="); found {
			names = append(names, key)
		}
	}
	names = append(names, "HOSTNAME") // injected by the daemon, not the image
	c.imageEnv = names
	return names
}

// proxyEnvMatches reports whether a container environment carries exactly
// the env-file's entries (the last one wins for a repeated name): each with
// the same value, and none of the agent's credential names left over from
// an earlier file.
func proxyEnvMatches(want, have, allowed []string) bool {
	values := func(entries []string) map[string]string {
		m := make(map[string]string, len(entries))
		for _, entry := range entries {
			key, value, _ := strings.Cut(entry, "=")
			m[key] = value
		}
		return m
	}
	wanted, current := values(want), values(have)
	for key, value := range wanted {
		if got, ok := current[key]; !ok || got != value {
			return false
		}
	}
	// A variable that left the env-file must leave the container too.
	// An entry still in the container has to be one the env-file asks for,
	// or one the image itself provides: the agent's credential names count
	// as file entries, so a stale credential from an earlier file forces
	// the recreation like any other removal. The container environment is
	// exposed to the internet; a removed value must not linger there.
	for key := range current {
		if _, ok := wanted[key]; ok {
			continue
		}
		if !slices.Contains(allowed, key) {
			return false
		}
	}
	return true
}

// envFilePath is the env-file that exposes the agent's credentials (and
// any future operator-level secrets) to Caddy via `--env-file`. It is not
// a mount: Docker copies its content into the container at creation.
func (c *Caddy) envFilePath() string {
	return filepath.Join(c.StateDir, "caddy.env")
}

// removeContainer stops + removes the Caddy container so EnsureRunning
// can recreate it with a fresh config. The bind-mounted /data dir is
// preserved on the host, so certificates issued by the previous build
// survive the cycle.
func (c *Caddy) removeContainer(ctx context.Context) error {
	// `docker rm -f` stops + removes in one shot.
	if out, err := exec.CommandContext(ctx, "docker", "rm", "-f", ContainerName).CombinedOutput(); err != nil {
		return fmt.Errorf("docker rm -f %s: %v: %s", ContainerName, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// SetImprezaCredentials updates the env-file Caddy reads at startup
// with the agent's own credentials so the bundled caddy-dns-impreza
// module can authenticate against the public API on every ACME DNS-01
// challenge.
//
// Phase 9.11d v2: replaces SetCloudflareToken. The CF token never
// reaches the agent — see caddy-dns-impreza/README.md for the
// threat-model rationale.
//
// Docker copies the env-file into the container when it is created, so
// neither a new file nor the restart below reaches a running container:
// the next EnsureRunning sees the environment differ and recreates it
// . To minimize unnecessary downtime this method:
//
//   - Writes the file at 0o600 only when content actually changes
//     (idempotent — the agent calls this on every startup with the
//     same values, no write needed).
//   - Restarts the Caddy container only when (a) the values changed
//     AND (b) the container is currently running. First-time set on
//     an unstarted Caddy is a no-op restart-wise; EnsureRunning will
//     pick up the env-file on its first launch.
//
// baseURL may be empty — the plugin falls back to the production
// default when so.
func (c *Caddy) SetImprezaCredentials(ctx context.Context, agentID, agentSecret, baseURL string) error {
	if err := c.ensureDirs(); err != nil {
		return err
	}
	envFile := c.envFilePath()

	// Compose desired content. Header comment so the file is
	// recognizable to operators reading it manually. Empty creds
	// clears the file entirely (e.g. agent in "no platform" mode).
	var desired string
	if agentID == "" || agentSecret == "" {
		desired = "# managed by impreza-agent — do not edit\n"
	} else {
		desired = fmt.Sprintf(
			"# managed by impreza-agent — do not edit\n%s=%s\n%s=%s\n%s=%s\n",
			ImprezaAgentIDEnvVar, agentID,
			ImprezaAgentSecretEnvVar, agentSecret,
			ImprezaAPIURLEnvVar, baseURL,
		)
	}

	current, _ := os.ReadFile(envFile)
	if string(current) == desired {
		return nil // no change → no restart
	}

	if err := os.WriteFile(envFile, []byte(desired), 0o600); err != nil {
		return fmt.Errorf("write caddy.env: %w", err)
	}

	// If Caddy is running, restart so it picks up the new env. If
	// not running, EnsureRunning will pick it up on next launch.
	if status, err := exec.CommandContext(ctx, "docker", "inspect",
		"--format", "{{.State.Status}}", ContainerName).CombinedOutput(); err == nil {
		if strings.TrimSpace(string(status)) == "running" {
			c.Log.Info("proxy: restarting caddy to load updated impreza credentials")
			if out, rErr := exec.CommandContext(ctx, "docker", "restart", ContainerName).CombinedOutput(); rErr != nil {
				return fmt.Errorf("docker restart %s after env-file update: %v: %s",
					ContainerName, rErr, strings.TrimSpace(string(out)))
			}
		}
	}
	return nil
}

// ApplyDeploymentRoutes writes the per-deployment Caddyfile fragment,
// regenerates the aggregate Caddyfile, and reloads Caddy. Passing an
// empty `routes` slice removes the deployment's fragment.
func (c *Caddy) ApplyDeploymentRoutes(ctx context.Context, deploymentID string, routes []Route) error {
	if err := c.guardRoutingSwitch(); err != nil {
		return err
	}
	if err := c.ensureDirs(); err != nil {
		return err
	}
	fragPath := filepath.Join(c.StateDir, "deployments", deploymentID+".caddy")

	if len(routes) == 0 {
		if err := os.Remove(fragPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove routing fragment: %w", err)
		}
	} else {
		// Refuse a malformed gate up front: writing it would either break
		// `caddy reload` for every deployment on the box or, worse, skip
		// the auth directive and serve a protected route publicly.
		for _, r := range routes {
			if err := validateBasicAuth(r.BasicAuth); err != nil {
				return fmt.Errorf("route %s: %w", r.Hostname+r.OnionAddr, err)
			}
			if err := r.Shield.validate(); err != nil {
				return fmt.Errorf("route %s: %w", r.Hostname+r.OnionAddr, err)
			}
		}
		body := renderFragment(deploymentID, routes)
		if err := os.WriteFile(fragPath, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write fragment %s: %w", fragPath, err)
		}
	}
	if err := c.regenerateCaddyfile(); err != nil {
		return err
	}
	if len(routes) == 0 {
		// Database-only hosts and internal jobs may never have created Caddy.
		// Prove absence through a successful daemon query; an unavailable
		// daemon or an existing stopped proxy is not proof of safe removal.
		absent, err := c.routingContainerAbsent(ctx)
		if err != nil {
			return err
		}
		if absent {
			return nil
		}
	}
	return c.reloadSwitch(ctx)
}

func (c *Caddy) routingContainerAbsent(ctx context.Context) (bool, error) {
	query := c.containerList
	if query == nil {
		query = func(ctx context.Context) ([]byte, error) {
			return exec.CommandContext(ctx, "docker", "container", "ls", "--all", "--filter", "name=^/"+ContainerName+"$", "--format", "{{.ID}}").Output()
		}
	}
	out, err := query(ctx)
	if err != nil {
		return false, fmt.Errorf("verify routing container before cleanup: %w", err)
	}
	return len(strings.TrimSpace(string(out))) == 0, nil
}

// RemoveDeploymentRoutes deletes the per-deployment fragment and reloads.
func (c *Caddy) RemoveDeploymentRoutes(ctx context.Context, deploymentID string) error {
	return c.ApplyDeploymentRoutes(ctx, deploymentID, nil)
}

// splitFragment breaks a fragment into its leading comments and its site
// blocks. The renderer's own output shape only: a block opens at column zero
// and closes with `}` at column zero. Anything else refuses — a fragment we
// cannot parse exactly is a fragment we must not rewrite.
func splitFragment(raw string) (header []string, blocks []string, err error) {
	raw = strings.TrimRight(raw, "\n")
	if raw == "" {
		return nil, nil, nil
	}
	lines := strings.Split(raw, "\n")
	i := 0
	for i < len(lines) && (strings.HasPrefix(lines[i], "#") || lines[i] == "") {
		i++
	}
	header = lines[:i]
	for i < len(lines) {
		if lines[i] == "" {
			i++
			continue
		}
		if strings.HasPrefix(lines[i], " ") || strings.HasPrefix(lines[i], "\t") {
			return nil, nil, fmt.Errorf("fragment block opens with indentation")
		}
		start := i
		for i < len(lines) && lines[i] != "}" {
			i++
		}
		if i >= len(lines) {
			return nil, nil, fmt.Errorf("fragment block is never closed")
		}
		i++
		blocks = append(blocks, strings.Join(lines[start:i], "\n"))
	}
	return header, blocks, nil
}

// SwitchHostname moves one hostname's site block from the source deployment's
// fragment to the target's, repointing its upstream. The block keeps its TLS
// directives verbatim: the certificate already exists for the hostname, and a
// re-issuance mid-switch would be downtime of our own making. The source keeps
// every other block (its onion mirror stays). Returns a rollback that restores
// both previous fragments and reloads; the caller decides when to run it.
var ErrRoutingRecoveryRequired = errors.New("routing recovery required")

func (c *Caddy) SwitchHostname(ctx context.Context, hostname, sourceID, targetID, upstream string) (undo func(context.Context) error, retErr error) {
	if err := c.guardRoutingSwitch(); err != nil {
		return nil, err
	}
	if err := c.ensureDirs(); err != nil {
		return nil, err
	}
	dir := filepath.Join(c.StateDir, "deployments")
	sourcePath := filepath.Join(dir, sourceID+".caddy")
	targetPath := filepath.Join(dir, targetID+".caddy")
	rawSource, err := os.ReadFile(sourcePath)
	if err != nil {
		return nil, fmt.Errorf("source fragment unreadable: %w", err)
	}
	header, blocks, err := splitFragment(string(rawSource))
	if err != nil {
		return nil, fmt.Errorf("source fragment shape unverified: %w", err)
	}
	var moved string
	kept := blocks[:0]
	for _, block := range blocks {
		if strings.HasPrefix(block, hostname+" {") {
			if moved != "" {
				return nil, fmt.Errorf("hostname appears twice in the source fragment")
			}
			moved = block
			continue
		}
		kept = append(kept, block)
	}
	if moved == "" {
		return nil, fmt.Errorf("the source is not serving the reviewed hostname")
	}
	lines := strings.Split(moved, "\n")
	found := false
	for i, line := range lines {
		if strings.HasPrefix(line, "  reverse_proxy ") {
			if found {
				return nil, fmt.Errorf("hostname block has more than one upstream")
			}
			lines[i] = "  reverse_proxy " + upstream
			found = true
		}
	}
	if !found {
		return nil, fmt.Errorf("hostname block has no upstream to repoint")
	}
	moved = strings.Join(lines, "\n")

	var rawTarget []byte
	if data, err := os.ReadFile(targetPath); err == nil {
		rawTarget = data
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("target fragment unreadable: %w", err)
	}
	targetHeader, targetBlocks, err := splitFragment(string(rawTarget))
	if err != nil {
		return nil, fmt.Errorf("target fragment shape unverified: %w", err)
	}
	targetBlocks = append(targetBlocks, moved)
	if err := c.beginRoutingSwitch(routingSwitchRecord{Version: 1, Hostname: hostname, Source: sourceID, Target: targetID, SourceBefore: rawSource, TargetBefore: rawTarget, TargetExisted: rawTarget != nil}); err != nil {
		return nil, errors.Join(ErrRoutingRecoveryRequired, err)
	}
	// Install rollback before the first mutation. A cancelled request must not
	// cancel recovery, and one failed restoration must not skip the other file.
	rollback := func(_ context.Context) error {
		recovery, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()
		var failures []error
		if rawTarget == nil {
			if err := os.Remove(targetPath); err != nil && !os.IsNotExist(err) {
				failures = append(failures, err)
			}
		} else if err := writeSwitchFile(targetPath, rawTarget); err != nil {
			failures = append(failures, err)
		}
		if err := writeSwitchFile(sourcePath, rawSource); err != nil {
			failures = append(failures, err)
		}
		if len(failures) > 0 {
			return errors.Join(failures...)
		}
		if err := c.regenerateCaddyfile(); err != nil {
			return err
		}
		if err := c.reloadSwitch(recovery); err != nil {
			return err
		}
		return c.CompleteHostnameSwitch(hostname, sourceID, targetID)
	}
	defer func() {
		if retErr != nil {
			if err := rollback(context.Background()); err != nil {
				retErr = errors.Join(retErr, ErrRoutingRecoveryRequired, err)
			}
		}
	}()

	write := func(path, deploymentID string, header, blocks []string) error {
		if len(blocks) == 0 {
			if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
				return err
			}
			return nil
		}
		var sb strings.Builder
		for _, line := range header {
			sb.WriteString(line + "\n")
		}
		if len(header) == 0 {
			fmt.Fprintf(&sb, "# deployment %s\n", deploymentID)
		}
		for _, block := range blocks {
			sb.WriteString(block + "\n\n")
		}
		return writeSwitchFile(path, []byte(sb.String()))
	}
	if err := write(sourcePath, sourceID, header, kept); err != nil {
		return nil, fmt.Errorf("write source fragment: %w", err)
	}
	if err := write(targetPath, targetID, targetHeader, targetBlocks); err != nil {
		return nil, fmt.Errorf("write target fragment: %w", err)
	}
	if err := c.regenerateCaddyfile(); err != nil {
		return nil, err
	}
	if err := c.reloadSwitch(ctx); err != nil {
		return nil, err
	}
	return rollback, nil
}

func writeSwitchFile(path string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".route-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err = f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err = f.Sync(); err != nil {
		f.Close()
		return err
	}
	if err = f.Close(); err != nil {
		return err
	}
	if err = os.Rename(f.Name(), path); err != nil {
		return err
	}
	return syncRoutingDir(filepath.Dir(path))
}

// A rejected configuration must never trigger a restart of the serving proxy.
func (c *Caddy) reloadSwitch(ctx context.Context) error {
	if c.switchReload != nil {
		return c.switchReload(ctx)
	}
	if err := exec.CommandContext(ctx, "docker", "exec", ContainerName, "caddy", "reload", "--config", "/etc/caddy/Caddyfile").Run(); err != nil {
		return fmt.Errorf("proxy did not accept routing: %w", err)
	}
	return nil
}

// regenerateCaddyfile reads all fragments in sorted order and writes a
// single Caddyfile to disk. Sorting by deployment_id keeps the output
// deterministic so `caddy reload` is a no-op when no routes changed.
func (c *Caddy) regenerateCaddyfile() error {
	dir := filepath.Join(c.StateDir, "deployments")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			entries = nil
		} else {
			return fmt.Errorf("read deployments dir: %w", err)
		}
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".caddy") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("# managed by impreza-agent — do not edit\n\n")
	anyShield := false
	anyFragment := false
	for _, n := range names {
		data, err := os.ReadFile(filepath.Join(dir, n))
		if err != nil {
			return fmt.Errorf("read routing fragment %s: %w", n, err)
		}
		secured, err := secureOnionFragment(string(data))
		if err != nil {
			return fmt.Errorf("secure onion fragment %s: %w", n, err)
		}
		anyShield = anyShield || fragmentUsesShield(secured)
		anyFragment = true
		sb.WriteString(secured)
		if !strings.HasSuffix(string(data), "\n") {
			sb.WriteByte('\n')
		}
		sb.WriteByte('\n')
	}
	body := sb.String()
	sb.Reset()
	sb.WriteString("# managed by impreza-agent — do not edit\n\n")
	// The metrics listener backs the per-deployment proxy counters
	// and the Shield telemetry; loopback inside the proxy container.
	sb.WriteString(shieldGlobalOptions(anyFragment))
	sb.WriteString(body)
	// Preserve the inode mounted into Caddy, but make its content durable before
	// the switch recovery record can be cleared.
	f, err := os.OpenFile(filepath.Join(c.StateDir, "Caddyfile"), os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	if _, err = f.WriteString(sb.String()); err != nil {
		f.Close()
		return err
	}
	if err = f.Sync(); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

// reload tells Caddy to re-read its Caddyfile in-place. Fast (no
// downtime) and idempotent on identical content. Falls back to
// `docker restart` if reload fails for any reason — better degraded
// than blocked.
func (c *Caddy) reload(ctx context.Context) error {
	out, err := exec.CommandContext(ctx, "docker", "exec", ContainerName,
		"caddy", "reload", "--config", "/etc/caddy/Caddyfile").CombinedOutput()
	if err == nil {
		return nil
	}
	c.Log.Warn("proxy: caddy reload failed, attempting restart",
		"err", err, "out", strings.TrimSpace(string(out)))
	if rOut, rErr := exec.CommandContext(ctx, "docker", "restart", ContainerName).CombinedOutput(); rErr != nil {
		return fmt.Errorf("caddy reload AND restart failed: reload=%v (%s); restart=%v (%s)",
			err, strings.TrimSpace(string(out)), rErr, strings.TrimSpace(string(rOut)))
	}
	return nil
}

// ensureDirs creates the proxy state dir tree at 0700.
func (c *Caddy) ensureDirs() error {
	for _, sub := range []string{"", "data", "config", "config/onion-private", "deployments"} {
		d := filepath.Join(c.StateDir, sub)
		if err := os.MkdirAll(d, 0o700); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
	}
	return nil
}

// renderFragment produces the Caddyfile snippet for one deployment.
// Each route becomes one OR two site blocks:
//
//   - a clearnet block when Hostname is set (auto-TLS via Let's Encrypt)
//   - an onion block when OnionAddr is set (`http://...onion {}`,
//     TLS skipped because Tor itself provides E2E encryption)
//
// A single Route with both fields produces both blocks, both
// reverse-proxying to the same upstream.
//
// When Route.TLSDNSProvider == "impreza" (Phase 9.11d v2) the tls
// directive is emitted as a block referencing the impreza DNS
// provider — Caddy then performs ACME DNS-01 instead of HTTP-01,
// tunneling the challenge through the operator's public API (which
// holds the upstream provider credentials IP-restricted to the
// control plane). This is what makes cert issuance / renewal survive
// a CDN proxy that's intercepting :80, without exposing any provider
// secret on the customer-controlled agent VPS.
func renderFragment(deploymentID string, routes []Route) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# deployment %s\n", deploymentID)
	for _, r := range routes {
		if r.Upstream == "" {
			continue
		}

		// Clearnet site block. TLSMode "none" is plain HTTP: the http://
		// site-address prefix is what actually disables Caddy auto-HTTPS —
		// a bare hostname 308-redirects to a certificate that cannot issue.
		if r.Hostname != "" {
			if r.TLSMode == "none" {
				fmt.Fprintf(&sb, "http://%s {\n", r.Hostname)
			} else {
				fmt.Fprintf(&sb, "%s {\n", r.Hostname)
			}
			switch r.TLSMode {
			case "letsencrypt", "":
				switch r.TLSDNSProvider {
				case "":
					// Default: HTTP-01 via the `tls <email>` shorthand,
					// same as before Phase 9.11d. Works for any hostname
					// that resolves directly to the agent's public IP.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s\n", r.TLSEmail)
					}
				case "impreza":
					// DNS-01 via the impreza-bundled libdns proxy. The
					// Caddy container reads its own credentials from
					// IMPREZA_AGENT_ID / IMPREZA_AGENT_SECRET / IMPREZA_API_URL
					// (set by SetImprezaCredentials in the env-file that
					// EnsureRunning passes). The plugin then POSTs to
					// /v1/agent/dns-challenge/{present,cleanup} on the
					// public API, which performs the CF TXT record
					// write/delete using server-side credentials.
					// Email is folded into the same block so cert contact
					// + DNS provider are both declared in one place.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s {\n", r.TLSEmail)
					} else {
						fmt.Fprintf(&sb, "  tls {\n")
					}
					fmt.Fprintf(&sb, "    dns impreza {env.%s} {env.%s} {env.%s}\n",
						ImprezaAgentIDEnvVar, ImprezaAgentSecretEnvVar, ImprezaAPIURLEnvVar)
					fmt.Fprintf(&sb, "  }\n")
				default:
					// Unknown provider — fall back to HTTP-01 rather
					// than emitting an invalid Caddy directive that
					// would prevent `caddy reload` from succeeding.
					// Agent logs will show the unrecognized value on
					// the next iteration when we extend this list.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s\n", r.TLSEmail)
					}
				}
			case "internal":
				fmt.Fprintf(&sb, "  tls internal\n")
			case "none":
				// HTTP-only — declaring host as `http://...` would do
				// the same; without TLSMode we let Caddy auto-TLS by
				// default. Operators who explicitly want HTTP can pick
				// TLSMode=none and Caddy will serve plain HTTP since
				// the absence of `tls` plus the http://... convention
				// is the standard Caddy way; we rely on Caddyfile
				// shorthand here.
			}
			writeBasicAuth(&sb, r.BasicAuth)
			// A Secure cookie attribute is only correct on TLS; plain-HTTP
			// clearnet (TLSMode none) drops it just like an onion origin.
			writeShieldDirectives(&sb, deploymentID, r.Shield, r.TLSMode != "none")
			writeProxyMetrics(&sb, deploymentID)
			// Dual-stack deployments advertise their onion mirror so Tor
			// Browser shows ".onion available" on the clearnet site. The
			// header is ignored on plain-HTTP clearnet (spec requires a
			// secure context), which is exactly where it would be useless.
			if r.OnionAddr != "" {
				fmt.Fprintf(&sb, "  header Onion-Location \"http://%s/\"\n", r.OnionAddr)
			}
			fmt.Fprintf(&sb, "  reverse_proxy %s\n", r.Upstream)
			fmt.Fprintf(&sb, "}\n")
		}

		// Onion block — Caddy's `http://...onion {}` form disables
		// auto-TLS for that site (Tor's protocol provides E2E
		// encryption end-to-end; a TLS cert on top would be useless
		// since Let's Encrypt can't issue for .onion anyway).
		if r.OnionAddr != "" {
			fmt.Fprintf(&sb, "http://%s {\n", r.OnionAddr)
			sb.WriteString("  bind unix//config/onion-private/http.sock|0600\n")
			writeBasicAuth(&sb, r.BasicAuth)
			// No Secure cookie attribute on plain-HTTP onion origins.
			writeShieldDirectives(&sb, deploymentID, r.Shield, false)
			writeProxyMetrics(&sb, deploymentID)
			fmt.Fprintf(&sb, "  reverse_proxy %s\n", r.Upstream)
			fmt.Fprintf(&sb, "}\n")
		}
	}
	return sb.String()
}

// writeBasicAuth emits the gate for a protected route. Validated upstream
// (ApplyDeploymentRoutes), so this only ever writes a safe bcrypt line.
func writeBasicAuth(sb *strings.Builder, b *BasicAuth) {
	if b == nil {
		return
	}
	fmt.Fprintf(sb, "  basic_auth {\n    %s %s\n  }\n", b.Username, b.BCryptHash)
}
