// Package proxy manages the host-wide reverse proxy that fronts
// every deployment with a hostname route. A single Caddy container
// (`impreza_caddy`) runs per host, joined to a shared Docker network
// (`impreza-proxy`) that deployment containers also join; Caddy
// forwards `hostname → container:port` and obtains Let's Encrypt
// certificates automatically.
//
// Persistence layout under stateDir/proxy/:
//
//	Caddyfile               # generated by concatenating fragments
//	data/                   # Caddy's cert + ACME state (mounted /data)
//	config/                 # Caddy's runtime config (mounted /config)
//	deployments/
//	    dpl_xxx.caddy       # per-deployment fragment
//	    dpl_yyy.caddy
//
// The agent calls EnsureNetwork + EnsureRunning before applying the
// first route; subsequent route changes only trigger Caddyfile
// regeneration + `caddy reload`.
package proxy

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// NetworkName is the shared Docker network Caddy + apps join.
	NetworkName = "impreza-proxy"
	// ContainerName is the singleton Caddy container per host.
	ContainerName = "impreza_caddy"
	// Image is the Caddy image. We ship a custom build that bundles
	// the caddy-dns-impreza module on top of caddy:<ver>-alpine so
	// Caddy can complete ACME DNS-01 challenges by proxying TXT-record
	// writes through the Impreza public API (the operator's CF token
	// stays IP-restricted on the control plane — see
	// caddy-dns-impreza/README.md for the rationale). The :2-cf tag
	// tracks the latest 2.x release of our image.
	//
	// Published to GitHub Container Registry by the
	// .github/workflows/caddy-image.yml workflow on every caddy-v<X.Y.Z>
	// tag; the ghcr.io/imprezahost/caddy package is public so customer
	// VPSes can pull it without credentials.
	Image = "ghcr.io/imprezahost/caddy:2-cf"
	// Env-var names the Caddy container reads to authenticate against
	// the Impreza public API on every DNS-01 present/cleanup. These
	// are set by SetImprezaCredentials via a bind-mounted env-file and
	// referenced from per-deployment fragments as
	// `dns impreza {env.IMPREZA_AGENT_ID} {env.IMPREZA_AGENT_SECRET}`.
	// Phase 9.11d v2 — replaces the CADDY_CF_API_TOKEN of v1 (which
	// exposed CF write access to every customer VPS).
	ImprezaAgentIDEnvVar     = "IMPREZA_AGENT_ID"
	ImprezaAgentSecretEnvVar = "IMPREZA_AGENT_SECRET"
	ImprezaAPIURLEnvVar      = "IMPREZA_API_URL"
)

// Route describes one hostname → upstream mapping the proxy programs.
// Set Hostname for a clearnet site (Caddy auto-TLS via Let's Encrypt),
// or OnionAddr for an onion service block, or both: a single Route
// can emit both fragments pointing at the same upstream.
type Route struct {
	// Hostname is the public clearnet name Caddy listens on (e.g.
	// vault.example.com). Leave empty for onion-only routes.
	Hostname string
	// OnionAddr is the .onion address Tor publishes (e.g.
	// abc...xyz.onion). When set, an `http://<addr> { ... }` block
	// is emitted alongside / instead of the clearnet block.
	OnionAddr string
	// Upstream is the `container:port` Caddy forwards to. The container
	// MUST be joined to NetworkName so Caddy can resolve it.
	Upstream string
	// TLSMode is "letsencrypt" | "internal" | "none". "letsencrypt" is
	// the only one wired in this phase; the others come later.
	TLSMode string
	// TLSEmail is optional contact for Let's Encrypt.
	TLSEmail string
	// TLSDNSProvider (Phase 9.11d) opts this route into ACME DNS-01
	// challenge using the named provider instead of the default
	// HTTP-01. Currently only "cloudflare" is implemented. The CF API
	// token must be available to the Caddy container via the env-var
	// CloudflareTokenEnvVar — see SetCloudflareToken.
	TLSDNSProvider string
}

// Caddy owns the host's reverse-proxy state.
type Caddy struct {
	StateDir string // <agent-state>/proxy
	Log      *slog.Logger
}

// New constructs a Caddy under <agentStateDir>/proxy.
func New(agentStateDir string, log *slog.Logger) *Caddy {
	return &Caddy{
		StateDir: filepath.Join(agentStateDir, "proxy"),
		Log:      log,
	}
}

// EnsureNetwork creates the shared Docker network if absent.
// Idempotent — repeated calls are cheap.
func (c *Caddy) EnsureNetwork(ctx context.Context) error {
	// `docker network inspect` exits 0 when present, non-zero otherwise.
	if out, err := exec.CommandContext(ctx, "docker", "network", "inspect", NetworkName).CombinedOutput(); err == nil {
		_ = out
		return nil
	}
	c.Log.Info("proxy: creating shared docker network", "network", NetworkName)
	if out, err := exec.CommandContext(ctx, "docker", "network", "create", NetworkName).CombinedOutput(); err != nil {
		return fmt.Errorf("docker network create %s: %v: %s", NetworkName, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// EnsureRunning starts the Caddy container if not already running.
// Idempotent. Mounts the Caddyfile + data dirs from StateDir.
//
// Phase 9.11d additions:
//   - Always passes `--env-file <stateDir>/proxy/caddy.env` so the
//     CloudflareTokenEnvVar set by SetCloudflareToken reaches Caddy
//     (the env-var is referenced from per-deployment fragments via
//     `{env.CADDY_CF_API_TOKEN}` for DNS-01 challenges).
//   - When an existing container is running but with the wrong Image
//     OR was created without the env-file mount (i.e. before the
//     9.11d agent upgrade), it is recreated so the new agent gets a
//     Caddy that can serve DNS-01 fragments. Data dir is bind-mounted
//     so existing certs survive the recreation.
func (c *Caddy) EnsureRunning(ctx context.Context) error {
	if err := c.ensureDirs(); err != nil {
		return err
	}
	// First write of the Caddyfile happens on first ApplyRoutes call;
	// EnsureRunning ensures it at least exists so Caddy doesn't crash
	// on missing config when there are zero deployments yet.
	caddyfile := filepath.Join(c.StateDir, "Caddyfile")
	if _, err := os.Stat(caddyfile); os.IsNotExist(err) {
		if err := os.WriteFile(caddyfile, []byte("# managed by impreza-agent — do not edit\n"), 0o644); err != nil {
			return fmt.Errorf("write empty Caddyfile: %w", err)
		}
	}

	// Ensure caddy.env exists (empty placeholder is fine — Caddy
	// tolerates the env-file containing zero vars). Set 0o600 because
	// when populated by SetCloudflareToken it holds an API token.
	envFile := c.envFilePath()
	if _, err := os.Stat(envFile); os.IsNotExist(err) {
		if err := os.WriteFile(envFile, []byte("# managed by impreza-agent — do not edit\n"), 0o600); err != nil {
			return fmt.Errorf("write empty caddy.env: %w", err)
		}
	}

	// Inspect the existing container if any. We want three pieces of
	// state in one round-trip: status (running / exited / etc.), image,
	// and whether the env-file is mounted. A mismatch on image OR a
	// missing env-file mount means the container was created by an
	// older agent and needs recreation to pick up 9.11d features.
	type containerInfo struct {
		Status   string
		Image    string
		HasEnvFM bool
	}
	var existing *containerInfo
	if out, err := exec.CommandContext(ctx, "docker", "inspect",
		"--format", "{{.State.Status}}|{{.Config.Image}}|{{range .HostConfig.Binds}}{{.}};{{end}}",
		ContainerName).CombinedOutput(); err == nil {
		parts := strings.SplitN(strings.TrimSpace(string(out)), "|", 3)
		if len(parts) == 3 {
			existing = &containerInfo{
				Status:   parts[0],
				Image:    parts[1],
				HasEnvFM: strings.Contains(parts[2], envFile+":"),
			}
		}
	}

	if existing != nil {
		needRecreate := existing.Image != Image || !existing.HasEnvFM
		if needRecreate {
			c.Log.Info("proxy: recreating caddy container with new image / env-file",
				"old_image", existing.Image, "new_image", Image, "had_env_file_mount", existing.HasEnvFM)
			if err := c.removeContainer(ctx); err != nil {
				return err
			}
		} else if existing.Status == "running" {
			return nil
		} else {
			// Exists, same shape, but not running — start it.
			c.Log.Info("proxy: starting existing caddy container", "state", existing.Status)
			if out, err := exec.CommandContext(ctx, "docker", "start", ContainerName).CombinedOutput(); err != nil {
				return fmt.Errorf("docker start %s: %v: %s", ContainerName, err, strings.TrimSpace(string(out)))
			}
			return nil
		}
	}

	// Doesn't exist (or was just removed for recreation) — run it.
	c.Log.Info("proxy: launching caddy container", "image", Image)
	args := []string{
		"run", "-d",
		"--name", ContainerName,
		"--restart", "unless-stopped",
		"--network", NetworkName,
		"-p", "80:80",
		"-p", "443:443",
		"-p", "443:443/udp", // HTTP/3
		"--env-file", envFile,
		"-v", caddyfile + ":/etc/caddy/Caddyfile:ro",
		"-v", filepath.Join(c.StateDir, "data") + ":/data",
		"-v", filepath.Join(c.StateDir, "config") + ":/config",
		Image,
	}
	if out, err := exec.CommandContext(ctx, "docker", args...).CombinedOutput(); err != nil {
		return fmt.Errorf("docker run caddy: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// envFilePath is the bind-mounted env-file that exposes
// CloudflareTokenEnvVar (and any future operator-level secrets) to
// Caddy via `--env-file`.
func (c *Caddy) envFilePath() string {
	return filepath.Join(c.StateDir, "caddy.env")
}

// removeContainer stops + removes the Caddy container so EnsureRunning
// can recreate it with a fresh config. The bind-mounted /data dir is
// preserved on the host, so certificates issued by the previous build
// survive the cycle.
func (c *Caddy) removeContainer(ctx context.Context) error {
	// `docker rm -f` stops + removes in one shot.
	if out, err := exec.CommandContext(ctx, "docker", "rm", "-f", ContainerName).CombinedOutput(); err != nil {
		return fmt.Errorf("docker rm -f %s: %v: %s", ContainerName, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// SetImprezaCredentials updates the env-file Caddy reads at startup
// with the agent's own credentials so the bundled caddy-dns-impreza
// module can authenticate against the public API on every ACME DNS-01
// challenge.
//
// Phase 9.11d v2: replaces SetCloudflareToken. The CF token never
// reaches the agent — see caddy-dns-impreza/README.md for the
// threat-model rationale.
//
// Caddy reads env-vars only at process start, so changing values
// after the container is up means a restart. To minimize unnecessary
// downtime this method:
//
//   - Writes the file at 0o600 only when content actually changes
//     (idempotent — the agent calls this on every startup with the
//     same values, no write needed).
//   - Restarts the Caddy container only when (a) the values changed
//     AND (b) the container is currently running. First-time set on
//     an unstarted Caddy is a no-op restart-wise; EnsureRunning will
//     pick up the env-file on its first launch.
//
// baseURL may be empty — the plugin falls back to the production
// default when so.
func (c *Caddy) SetImprezaCredentials(ctx context.Context, agentID, agentSecret, baseURL string) error {
	if err := c.ensureDirs(); err != nil {
		return err
	}
	envFile := c.envFilePath()

	// Compose desired content. Header comment so the file is
	// recognizable to operators reading it manually. Empty creds
	// clears the file entirely (e.g. agent in "no platform" mode).
	var desired string
	if agentID == "" || agentSecret == "" {
		desired = "# managed by impreza-agent — do not edit\n"
	} else {
		desired = fmt.Sprintf(
			"# managed by impreza-agent — do not edit\n%s=%s\n%s=%s\n%s=%s\n",
			ImprezaAgentIDEnvVar, agentID,
			ImprezaAgentSecretEnvVar, agentSecret,
			ImprezaAPIURLEnvVar, baseURL,
		)
	}

	current, _ := os.ReadFile(envFile)
	if string(current) == desired {
		return nil // no change → no restart
	}

	if err := os.WriteFile(envFile, []byte(desired), 0o600); err != nil {
		return fmt.Errorf("write caddy.env: %w", err)
	}

	// If Caddy is running, restart so it picks up the new env. If
	// not running, EnsureRunning will pick it up on next launch.
	if status, err := exec.CommandContext(ctx, "docker", "inspect",
		"--format", "{{.State.Status}}", ContainerName).CombinedOutput(); err == nil {
		if strings.TrimSpace(string(status)) == "running" {
			c.Log.Info("proxy: restarting caddy to load updated impreza credentials")
			if out, rErr := exec.CommandContext(ctx, "docker", "restart", ContainerName).CombinedOutput(); rErr != nil {
				return fmt.Errorf("docker restart %s after env-file update: %v: %s",
					ContainerName, rErr, strings.TrimSpace(string(out)))
			}
		}
	}
	return nil
}

// ApplyDeploymentRoutes writes the per-deployment Caddyfile fragment,
// regenerates the aggregate Caddyfile, and reloads Caddy. Passing an
// empty `routes` slice removes the deployment's fragment.
func (c *Caddy) ApplyDeploymentRoutes(ctx context.Context, deploymentID string, routes []Route) error {
	if err := c.ensureDirs(); err != nil {
		return err
	}
	fragPath := filepath.Join(c.StateDir, "deployments", deploymentID+".caddy")

	if len(routes) == 0 {
		_ = os.Remove(fragPath)
	} else {
		body := renderFragment(deploymentID, routes)
		if err := os.WriteFile(fragPath, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write fragment %s: %w", fragPath, err)
		}
	}
	if err := c.regenerateCaddyfile(); err != nil {
		return err
	}
	return c.reload(ctx)
}

// RemoveDeploymentRoutes deletes the per-deployment fragment and reloads.
func (c *Caddy) RemoveDeploymentRoutes(ctx context.Context, deploymentID string) error {
	return c.ApplyDeploymentRoutes(ctx, deploymentID, nil)
}

// regenerateCaddyfile reads all fragments in sorted order and writes a
// single Caddyfile to disk. Sorting by deployment_id keeps the output
// deterministic so `caddy reload` is a no-op when no routes changed.
func (c *Caddy) regenerateCaddyfile() error {
	dir := filepath.Join(c.StateDir, "deployments")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			entries = nil
		} else {
			return fmt.Errorf("read deployments dir: %w", err)
		}
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".caddy") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("# managed by impreza-agent — do not edit\n\n")
	for _, n := range names {
		data, err := os.ReadFile(filepath.Join(dir, n))
		if err != nil {
			c.Log.Warn("proxy: skipping unreadable fragment", "name", n, "err", err)
			continue
		}
		sb.Write(data)
		if !strings.HasSuffix(string(data), "\n") {
			sb.WriteByte('\n')
		}
		sb.WriteByte('\n')
	}
	return os.WriteFile(filepath.Join(c.StateDir, "Caddyfile"), []byte(sb.String()), 0o644)
}

// reload tells Caddy to re-read its Caddyfile in-place. Fast (no
// downtime) and idempotent on identical content. Falls back to
// `docker restart` if reload fails for any reason — better degraded
// than blocked.
func (c *Caddy) reload(ctx context.Context) error {
	out, err := exec.CommandContext(ctx, "docker", "exec", ContainerName,
		"caddy", "reload", "--config", "/etc/caddy/Caddyfile").CombinedOutput()
	if err == nil {
		return nil
	}
	c.Log.Warn("proxy: caddy reload failed, attempting restart",
		"err", err, "out", strings.TrimSpace(string(out)))
	if rOut, rErr := exec.CommandContext(ctx, "docker", "restart", ContainerName).CombinedOutput(); rErr != nil {
		return fmt.Errorf("caddy reload AND restart failed: reload=%v (%s); restart=%v (%s)",
			err, strings.TrimSpace(string(out)), rErr, strings.TrimSpace(string(rOut)))
	}
	return nil
}

// ensureDirs creates the proxy state dir tree at 0700.
func (c *Caddy) ensureDirs() error {
	for _, sub := range []string{"", "data", "config", "deployments"} {
		d := filepath.Join(c.StateDir, sub)
		if err := os.MkdirAll(d, 0o700); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
	}
	return nil
}

// renderFragment produces the Caddyfile snippet for one deployment.
// Each route becomes one OR two site blocks:
//
//   - a clearnet block when Hostname is set (auto-TLS via Let's Encrypt)
//   - an onion block when OnionAddr is set (`http://...onion {}`,
//     TLS skipped because Tor itself provides E2E encryption)
//
// A single Route with both fields produces both blocks, both
// reverse-proxying to the same upstream.
//
// When Route.TLSDNSProvider == "impreza" (Phase 9.11d v2) the tls
// directive is emitted as a block referencing the impreza DNS
// provider — Caddy then performs ACME DNS-01 instead of HTTP-01,
// tunneling the challenge through the operator's public API (which
// holds the upstream provider credentials IP-restricted to the
// control plane). This is what makes cert issuance / renewal survive
// a CDN proxy that's intercepting :80, without exposing any provider
// secret on the customer-controlled agent VPS.
func renderFragment(deploymentID string, routes []Route) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# deployment %s\n", deploymentID)
	for _, r := range routes {
		if r.Upstream == "" {
			continue
		}

		// Clearnet site block.
		if r.Hostname != "" {
			fmt.Fprintf(&sb, "%s {\n", r.Hostname)
			switch r.TLSMode {
			case "letsencrypt", "":
				switch r.TLSDNSProvider {
				case "":
					// Default: HTTP-01 via the `tls <email>` shorthand,
					// same as before Phase 9.11d. Works for any hostname
					// that resolves directly to the agent's public IP.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s\n", r.TLSEmail)
					}
				case "impreza":
					// DNS-01 via the impreza-bundled libdns proxy. The
					// Caddy container reads its own credentials from
					// IMPREZA_AGENT_ID / IMPREZA_AGENT_SECRET / IMPREZA_API_URL
					// (set by SetImprezaCredentials + the env-file mount
					// in EnsureRunning). The plugin then POSTs to
					// /v1/agent/dns-challenge/{present,cleanup} on the
					// public API, which performs the CF TXT record
					// write/delete using server-side credentials.
					// Email is folded into the same block so cert contact
					// + DNS provider are both declared in one place.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s {\n", r.TLSEmail)
					} else {
						fmt.Fprintf(&sb, "  tls {\n")
					}
					fmt.Fprintf(&sb, "    dns impreza {env.%s} {env.%s} {env.%s}\n",
						ImprezaAgentIDEnvVar, ImprezaAgentSecretEnvVar, ImprezaAPIURLEnvVar)
					fmt.Fprintf(&sb, "  }\n")
				default:
					// Unknown provider — fall back to HTTP-01 rather
					// than emitting an invalid Caddy directive that
					// would prevent `caddy reload` from succeeding.
					// Agent logs will show the unrecognized value on
					// the next iteration when we extend this list.
					if r.TLSEmail != "" {
						fmt.Fprintf(&sb, "  tls %s\n", r.TLSEmail)
					}
				}
			case "internal":
				fmt.Fprintf(&sb, "  tls internal\n")
			case "none":
				// HTTP-only — declaring host as `http://...` would do
				// the same; without TLSMode we let Caddy auto-TLS by
				// default. Operators who explicitly want HTTP can pick
				// TLSMode=none and Caddy will serve plain HTTP since
				// the absence of `tls` plus the http://... convention
				// is the standard Caddy way; we rely on Caddyfile
				// shorthand here.
			}
			fmt.Fprintf(&sb, "  reverse_proxy %s\n", r.Upstream)
			fmt.Fprintf(&sb, "}\n")
		}

		// Onion block — Caddy's `http://...onion {}` form disables
		// auto-TLS for that site (Tor's protocol provides E2E
		// encryption end-to-end; a TLS cert on top would be useless
		// since Let's Encrypt can't issue for .onion anyway).
		if r.OnionAddr != "" {
			fmt.Fprintf(&sb, "http://%s {\n", r.OnionAddr)
			fmt.Fprintf(&sb, "  reverse_proxy %s\n", r.Upstream)
			fmt.Fprintf(&sb, "}\n")
		}
	}
	return sb.String()
}
