package proxy

// Tor manages a single hidden-services-only Tor daemon container per
// host, sister to Caddy. Each deployment that opts into onion routing
// gets its own HiddenServiceDir under
// <stateDir>/proxy/tor/services/<deployment_id>/; Tor writes the
// .onion address into a `hostname` file there, which the agent reads
// back and reports to the control plane.
//
// All hidden services map to the local Caddy container on port 80 —
// Caddy distinguishes onion vs clearnet by Host header (since Tor
// preserves the onion address as the Host).
//
// Persistence layout under <stateDir>/proxy/tor/:
//
//	torrc                       # generated by the agent
//	data/                       # Tor data dir (controller state, descriptors)
//	services/
//	    <deployment_id>/
//	        hostname            # the .onion (Tor writes this)
//	        hs_ed25519_secret_key
//	        hs_ed25519_public_key
//
// Reloads via SIGHUP — Tor re-reads torrc + provisions new services
// without dropping established circuits for existing services.

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	// TorContainer is the singleton Tor container per host.
	TorContainer = "impreza_tor"
	// TorImage — small Alpine-based image that just runs `tor`. Pinned
	// to a tag in production; `:latest` is fine for the MVP since we
	// don't depend on specific features beyond v3 hidden services
	// (default in any Tor >= 0.3.5, ~2018).
	TorImage = "osminogin/tor-simple:latest"
	// Default upstream Caddy listens on inside impreza-proxy.
	torUpstream = ContainerName + ":80"
	// How long we wait for Tor to publish a hostname file after
	// adding a HiddenServiceDir. v3 publishes within a few seconds
	// on a warm Tor (already bootstrapped); first deploy on a cold
	// Tor can take 30-60s.
	hostnamePollTimeout  = 90 * time.Second
	hostnamePollInterval = 1 * time.Second
)

// Tor owns the host's hidden-service-mode Tor instance.
type Tor struct {
	StateDir string // <agent-state>/proxy/tor
	Log      *slog.Logger
}

// NewTor builds a Tor manager rooted at <agentStateDir>/proxy/tor.
func NewTor(agentStateDir string, log *slog.Logger) *Tor {
	return &Tor{
		StateDir: filepath.Join(agentStateDir, "proxy", "tor"),
		Log:      log,
	}
}

// isRunning returns true if the Tor container is up. We use this from
// ProvisionHiddenService to pick the cold-start vs. warm-reload path.
func (t *Tor) isRunning(ctx context.Context) bool {
	out, err := exec.CommandContext(ctx, "docker", "inspect",
		"--format", "{{.State.Status}}", TorContainer).CombinedOutput()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(out)) == "running"
}

// launch (re)starts the Tor container with whatever torrc is on disk.
// Removes any stopped/exited container of the same name first — that
// path runs when an earlier launch crashed and left a corpse behind.
func (t *Tor) launch(ctx context.Context) error {
	// Best-effort cleanup of any stopped instance.
	_ = exec.CommandContext(ctx, "docker", "rm", "-f", TorContainer).Run()

	t.Log.Info("proxy/tor: launching tor container with current torrc")
	args := []string{
		"run", "-d",
		"--name", TorContainer,
		"--restart", "unless-stopped",
		"--network", NetworkName,
		// Run as root inside the container so Tor can chown the
		// HiddenServiceDirs to itself if needed. The osminogin image
		// is happy with this.
		"-u", "root",
		"-v", filepath.Join(t.StateDir, "torrc") + ":/etc/tor/torrc:ro",
		"-v", filepath.Join(t.StateDir, "data") + ":/var/lib/tor",
		"-v", filepath.Join(t.StateDir, "services") + ":/var/lib/tor/services",
		TorImage,
	}
	if out, err := exec.CommandContext(ctx, "docker", args...).CombinedOutput(); err != nil {
		return fmt.Errorf("docker run tor: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// ProvisionHiddenService creates a HiddenServiceDir for the given
// deployment and ensures Tor is running with that service in its
// torrc. Returns the resulting .onion address.
//
// The order matters: we write torrc with the new entry FIRST, then
// either launch Tor (cold path — it reads the fresh torrc on
// startup, provisions the service during bootstrap) or SIGHUP an
// already-running Tor (warm path — it re-reads + provisions). This
// avoids the race where a SIGHUP arrives before Tor's signal
// handlers are installed and is silently dropped.
//
// `upstreamPort` is the port Tor forwards to on `impreza_caddy`
// inside `impreza-proxy`. For a deployment serving HTTP through
// Caddy, this is 80.
func (t *Tor) ProvisionHiddenService(ctx context.Context, deploymentID string, upstreamPort int) (string, error) {
	if err := t.ensureDirs(); err != nil {
		return "", err
	}
	svcDir := filepath.Join(t.StateDir, "services", deploymentID)
	if err := os.MkdirAll(svcDir, 0o700); err != nil {
		return "", fmt.Errorf("mkdir hidden service dir: %w", err)
	}

	// torrc reflects the on-disk service list — including the new
	// entry just created above — before we touch the container.
	if err := t.regenerateTorrc(); err != nil {
		return "", err
	}

	if !t.isRunning(ctx) {
		// Cold path: launch Tor with the fresh torrc. It provisions
		// the service during normal startup; no SIGHUP needed.
		if err := t.launch(ctx); err != nil {
			return "", err
		}
	} else {
		// Warm path: Tor is already bootstrapped, just nudge it.
		hupCtx, cancelHup := context.WithTimeout(ctx, 5*time.Second)
		out, err := exec.CommandContext(hupCtx, "docker", "kill", "-s", "HUP", TorContainer).CombinedOutput()
		cancelHup()
		if err != nil {
			t.Log.Warn("proxy/tor: SIGHUP failed, restarting tor container",
				"err", err, "out", strings.TrimSpace(string(out)))
			rCtx, cancelR := context.WithTimeout(ctx, 30*time.Second)
			rOut, rErr := exec.CommandContext(rCtx, "docker", "restart", TorContainer).CombinedOutput()
			cancelR()
			if rErr != nil {
				return "", fmt.Errorf("SIGHUP failed AND restart failed: %v: %s",
					rErr, strings.TrimSpace(string(rOut)))
			}
		}
	}

	// Poll for the hostname file. Tor writes it the moment it
	// successfully generates the v3 keys; descriptor publication to
	// the directory authorities happens after, but we already have
	// the onion address by then.
	hostnameFile := filepath.Join(svcDir, "hostname")
	deadline := time.Now().Add(hostnamePollTimeout)
	for {
		if data, err := os.ReadFile(hostnameFile); err == nil {
			onion := strings.TrimSpace(string(data))
			if onion != "" {
				return onion, nil
			}
		}
		if time.Now().After(deadline) {
			return "", fmt.Errorf("hidden service hostname not published within %s — check `docker logs %s`",
				hostnamePollTimeout, TorContainer)
		}
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-time.After(hostnamePollInterval):
		}
	}
}

// RemoveHiddenService deletes the deployment's HiddenServiceDir and
// reloads Tor. Safe to call when no service exists for that
// deployment (the regenerated torrc just won't include the entry).
//
// Removing the dir also drops the onion's keys, so a re-deploy of
// the same deployment_id will get a NEW .onion. (If we want sticky
// onions across reinstalls we keep the keys around — TODO Phase 9.5.1.)
func (t *Tor) RemoveHiddenService(ctx context.Context, deploymentID string) error {
	svcDir := filepath.Join(t.StateDir, "services", deploymentID)
	if err := os.RemoveAll(svcDir); err != nil {
		return fmt.Errorf("remove hidden service dir: %w", err)
	}
	if err := t.regenerateTorrc(); err != nil {
		return err
	}
	hupCtx, cancelHup := context.WithTimeout(ctx, 5*time.Second)
	defer cancelHup()
	out, err := exec.CommandContext(hupCtx, "docker", "kill", "-s", "HUP", TorContainer).CombinedOutput()
	if err != nil {
		t.Log.Warn("proxy/tor: SIGHUP on remove failed",
			"err", err, "out", strings.TrimSpace(string(out)))
		// Non-fatal — service is dropped from filesystem; Tor will
		// catch up on next restart.
	}
	return nil
}

// regenerateTorrc emits a torrc file enumerating every
// HiddenServiceDir currently present on disk. Each subdirectory of
// services/ becomes one HiddenServiceDir block; sort lexically so
// the output is deterministic.
func (t *Tor) regenerateTorrc() error {
	servicesDir := filepath.Join(t.StateDir, "services")
	entries, err := os.ReadDir(servicesDir)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read services dir: %w", err)
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("# managed by impreza-agent — do not edit\n\n")
	// Defaults: only hidden services, no SOCKS / control port exposed.
	sb.WriteString("SocksPort 0\n")
	sb.WriteString("RunAsDaemon 0\n")
	sb.WriteString("Log notice stdout\n")
	sb.WriteString("DataDirectory /var/lib/tor\n\n")

	for _, n := range names {
		// Path is the container-internal path (mounted from the host).
		fmt.Fprintf(&sb, "HiddenServiceDir /var/lib/tor/services/%s\n", n)
		fmt.Fprintf(&sb, "HiddenServicePort 80 %s\n", torUpstream)
		sb.WriteString("HiddenServiceVersion 3\n\n")
	}

	return os.WriteFile(filepath.Join(t.StateDir, "torrc"), []byte(sb.String()), 0o644)
}

// ensureDirs creates the tor state dir tree.
func (t *Tor) ensureDirs() error {
	for _, sub := range []string{"", "data", "services"} {
		d := filepath.Join(t.StateDir, sub)
		if err := os.MkdirAll(d, 0o700); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
	}
	return nil
}

// OnionRouteFragment builds a Caddyfile entry that serves the given
// .onion address by reverse-proxying it to the deployment's
// upstream. Caddy's `http://...` prefix disables auto-TLS — Tor
// already provides end-to-end encryption for the onion connection.
func OnionRouteFragment(onion, upstream string) string {
	if onion == "" || upstream == "" {
		return ""
	}
	return fmt.Sprintf("http://%s {\n  reverse_proxy %s\n}\n", onion, upstream)
}
