// Command impreza-agent is the Impreza Platform daemon.
//
// One binary runs on every managed server (Impreza-provisioned or
// bring-your-own) and connects back to the control plane via HTTP
// long-poll. It executes deploy / update / rollback / health-check
// commands and reports outcomes.
//
// Subcommands:
//
//	bootstrap   Exchange a one-time token for permanent credentials.
//	run         Run the long-poll loop (entry point of the systemd unit).
//	doctor      Diagnose config / network / credential issues.
//	version     Print the build version.
//
// Build with `make build`. Distribution via .deb / .rpm packages
// generated by CI using the nfpm config in `packaging/`.
package main

import (
	"os"

	"github.com/imprezahost/impreza-devkit/agent-go/cmd"
)

// version is set via build-time ldflags:
//
//	go build -ldflags "-X main.version=0.1.0" .
var version = "dev"

func main() {
	cmd.SetVersion(version)
	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
